spring:
  config:
    import: configserver:${CONFIG_SERVER_URL:https://config-server-production.up.railway.app}
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 5
        initial-interval: 2000
  application:
    name: vendas-flux-backend
  profiles:
    active: dev

server:
  port: ${PORT:8081}
