spring:
  config:
    import: configserver:${CONFIG_SERVER_URL:https://config-server-production.up.railway.app}
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 5000
        max-interval: 15000
        multiplier: 1.5
  application:
    name: vendas-flux-backend
  profiles:
    active: dev

server:
  port: ${PORT:8081}
